cx-flow:
  bug-tracker: JIRA
  filter-severity:
  - Critical
  - High
  - Medium
  # - Low
  # - Information
  filter-category:
  # - Code_Injection
  # - Client_DOM_Stored_XSS
  # filter-cwe:
  filter-status:
  - Urgent
  - Confirmed
  # - Not Exploitable
  - Proposed Not Exploitable
  # - To Verify
  mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  enabled-vulnerability-scanners:
  - sca
  - sast
  - kics
  # thresholds:
  # - new: 1
  # - critical: 2
  # - high: 10
  # - medium: 50
  # - low: 100
   
cxone:
  url: https://eu.ast.checkmarx.net
  acl: https://eu.iam.checkmarx.net
  tenant: 
  # CXONE Credentials, use api key OR OAUTh Client
  # # --- Using api key
  # apikey: 
  # clientid: ast-app
  # granttype: refresh_token
  # # --- Using OAUTH client
  # apikey: 
  # clientid: 
  # granttype: client_credentials
  # Proxy. Url with port
  proxy_url: 
  proxy_username: 
  proxy_password:      

checkmarx:
  incremental: false

sca:
  filter-severity:
  - Critical
  - High
  - Medium
  # - Low
  # - Information
  filter-status:
  - Urgent
  - Confirmed
  # - Not Exploitable
  - Proposed Not Exploitable
  # - To Verify
  filter-score: 9.0
  # filter-dependency-type: Direct
  # filter-ignore-dev-test: false
  # filter-policy-violation: true
  # filter-exploitable-path: false
  # thresholds:
  # - new: 1
  # - critical: 2
  # - high: 10
  # - medium: 50
  # - low: 100
  # thresholds-score: 9.0

kics:  
  filter-severity:
  - Critical
  - High
  - Medium
  # - Low
  # - Information
  filter-status:
  - Urgent
  - Confirmed
  # - Not Exploitable
  - Proposed Not Exploitable
  # - To Verify
  # filter-category:
  # - APT-GET Not Avoiding Additional Packages
  # - Missing User Instruction
  # thresholds:
  # - new: 1
  # - critical: 2
  # - high: 10
  # - medium: 50
  # - low: 100
 
jira:
  url: 
  username: 
  token: 
  verify_ssl: 
  cloud: 
  timeout: 
  project: 
  issue-type: Bug
  priorities:
    Critical: Highest
    High: High
    Medium: Medium
    Low: Low
    Informational: Lowest
  open-transition: In Progress
  close-transition: Done
  open-status:
    - To Do
    - Backlog
    - Selected for Development
    - In Progress
  closed-status:
    - Done
  # fields:
  #   - type: result
  #     name: category
  #     jira-field-name: Epic Name
  #     jira-field-type: text
